#! /bin/bash

#STEP-1: Go to opt directory
cd /opt/

#STEP-2: Install Java 17 (Required for SonarQube)
sudo yum install java-17-amazon-corretto -y

#STEP-3: Install wget and unzip
sudo yum install wget unzip -y

#STEP-4: Download SonarQube
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.3.79811.zip

#STEP-5: Unzip SonarQube
sudo unzip sonarqube-9.9.3.79811.zip

#STEP-6: Rename directory (optional but cleaner)
sudo mv sonarqube-9.9.3.79811 sonarqube

#STEP-7: Create sonar user
sudo useradd sonar

#STEP-8: Change ownership
sudo chown sonar:sonar /opt/sonarqube -R

#STEP-9: Give permissions
sudo chmod 775 /opt/sonarqube -R

#STEP-10: Switch to sonar user
su - sonar

#After switching run manually
#cd /opt/sonarqube/bin/linux-x86-64
#sh sonar.sh start

#Default Login
#user=admin
#password=admin
